name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We appreciate your ideas to improve the SEO Intelligence system.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I also considered...

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the specific use case for this feature
      placeholder: |
        **Who would use it:** SEO analysts
        **How often:** Daily
        **What problem it solves:** Reduces manual work by...
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How important is this feature to you?
      options:
        - Critical - Blocking my use of the tool
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Which component does this relate to?
      multiple: true
      options:
        - Workflow logic
        - Data collection (DataForSEO)
        - Data storage (Supabase/Sheets)
        - Opportunity scoring
        - Keyword clustering
        - Content briefs
        - Alerts/monitoring
        - Cost optimization
        - Documentation
        - Testing
        - Other

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas about how to implement this, share them here
      placeholder: This could be implemented by...

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature is to implement?
      options:
        - Low - Configuration change
        - Medium - New node or modification
        - High - Major workflow change
        - Unknown

  - type: dropdown
    id: cost-impact
    attributes:
      label: API Cost Impact
      description: Will this feature increase API costs?
      options:
        - No additional API calls
        - Minimal cost increase
        - Moderate cost increase
        - Significant cost increase
        - Unknown

  - type: textarea
    id: examples
    attributes:
      label: Examples or Mockups
      description: If applicable, add examples, mockups, or links to similar features

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and feature requests
          required: true
        - label: This feature aligns with the project's goals
          required: false
        - label: I am willing to help implement or test this feature
          required: false
